spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mocktest
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  application:
    name: lab3
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org:
      hibernate:
        SQL: info   # Set SQL logging to info level
        type: warn  # Set type logging to warn level to reduce verbosity


server:
  port: 9900
