version: '3'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: lab5
      POSTGRES_USER: binod
      POSTGRES_PASSWORD: binod@123
    ports:
      - "5431:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - mynet

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - mynet

volumes:
  dbdata:

networks:
  mynet:
